import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { spawn } from "node:child_process";
import { claude } from "./claude.js";
import { config } from "../config.js";

// Builds the director's bespoke "custom" scenes at render time: an agentic Opus session
// writes the component into studio/src/auto/generated/; we then typecheck, render a still
// of each component and have Opus LOOK at it (the CLAUDE.md "verify visually" rule, applied
// to the robot). Any failure deletes this build's files and rebuilds the registry — a render
// can never break, and the studio project can't be left dirty.
//
// The registry (generated/index.ts) is MACHINE-GENERATED here — agents never touch it.
// Keys are "<videoId>/<Name>" so two videos' components can't collide.

function run(cmd: string, args: string[], cwd: string, timeoutMs = 240_000): Promise<{ ok: boolean; out: string }> {
  return new Promise((res) => {
    const p = spawn(cmd, args, { cwd, shell: process.platform === "win32" });
    let out = "";
    const timer = setTimeout(() => {
      p.kill("SIGKILL");
      res({ ok: false, out: `${cmd} timed out after ${Math.round(timeoutMs / 1000)}s` });
    }, timeoutMs);
    p.stdout.on("data", (d) => (out += d));
    p.stderr.on("data", (d) => (out += d));
    p.on("error", () => { clearTimeout(timer); res({ ok: false, out: `${cmd} failed to run` }); });
    p.on("close", (code) => { clearTimeout(timer); res({ ok: code === 0, out }); });
  });
}

async function tsc(studio: string): Promise<{ ok: boolean; errors: string }> {
  const r = await run("npx", ["tsc", "--noEmit"], studio);
  return { ok: r.ok, errors: r.out.slice(0, 2000) };
}

type Gen = { file: string; videoId: string; ts: number; name: string };

async function listGenerated(dir: string): Promise<Gen[]> {
  const files = (await readdir(dir).catch(() => [] as string[])).filter((f) => /^reel-\d+-[A-Za-z0-9]+\.tsx$/.test(f));
  return files.map((f) => {
    const m = f.match(/^(reel-(\d+))-([A-Za-z0-9]+)\.tsx$/)!;
    return { file: f, videoId: m[1], ts: Number(m[2]), name: m[3] };
  });
}

async function writeRegistry(dir: string): Promise<void> {
  const comps = await listGenerated(dir);
  const src = [
    'import type * as React from "react";',
    "",
    "// MACHINE-GENERATED by bot/src/lib/studio.ts — do not edit by hand.",
    "// AutoReel resolves {\"kind\":\"custom\",\"name\":\"<videoId>/<Name>\"} via GENERATED[name].",
    ...comps.map((c, i) => `import C${i} from "./${c.file.replace(/\.tsx$/, "")}";`),
    "",
    "export const GENERATED: Record<string, React.FC<any>> = {",
    ...comps.map((c, i) => `  "${c.videoId}/${c.name}": C${i},`),
    "};",
    "",
  ].join("\n");
  await writeFile(resolve(dir, "index.ts"), src);
}

// keep only the newest KEEP videos' components — one stale component breaking (Remotion
// upgrade, API drift) would otherwise block every future custom build via project-wide tsc
async function pruneGenerated(dir: string, keep = 5): Promise<void> {
  const comps = await listGenerated(dir);
  const ids = [...new Set(comps.map((c) => c.ts))].sort((a, b) => b - a);
  const dead = new Set(ids.slice(keep));
  for (const c of comps) if (dead.has(c.ts)) await unlink(resolve(dir, c.file)).catch(() => {});
}

// render one still of the custom scene (mid-animation, springs settled) for the visual gate
async function renderStill(studio: string, videoId: string, c: any): Promise<string | null> {
  const rel = `out/verify-${videoId}-${c.name}.png`;
  const propsPath = resolve(studio, "out", `verify-${videoId}-${c.name}.props.json`);
  await mkdir(resolve(studio, "out"), { recursive: true });
  await writeFile(
    propsPath,
    JSON.stringify({
      videoSrc: "",
      captions: [],
      scenes: [{ ...c, name: `${videoId}/${c.name}`, startMs: 0, endMs: 3000 }],
      accent: "cyan",
    }),
  );
  const r = await run("npx", ["remotion", "still", "AutoReel", rel, `--props=${propsPath}`, "--frame=45", "--scale=0.5"], studio);
  if (!r.ok) console.error(`verify still failed for ${c.name}:`, r.out.slice(-300));
  return r.ok ? rel : null;
}

const AGENT_TOOLS = ["Read", "Write", "Edit", "Glob", "Grep"];

export async function buildCustomScenes(scenes: any[], videoId: string): Promise<any[]> {
  const customs = scenes.filter((s) => s.kind === "custom" && s.name && s.spec);
  if (!customs.length) return scenes.filter((s) => s.kind !== "custom");

  const studio = config.studioDir;
  const dir = resolve(studio, "src/auto/generated");
  await pruneGenerated(dir);
  await writeRegistry(dir); // registry reflects the pruned set before we build on top of it
  const before = new Set((await listGenerated(dir)).map((c) => c.file));

  const brief = customs
    .map((c) => `- name: ${c.name}\n  spec: ${c.spec}\n  props it will receive: ${JSON.stringify(c.props ?? {})}`)
    .join("\n");

  const prompt = `You are building bespoke Remotion scene components for ONE video (id ${videoId})
inside this studio project (cwd = studio root). Build these:
${brief}

REQUIREMENTS (all mandatory):
1. Read src/auto/theme.ts and src/auto/fx.tsx first — reuse their pieces.
2. For each component: create src/auto/generated/${videoId}-<Name>.tsx with a DEFAULT export
   React.FC that takes the props above. Visual language: dark glassy panels, hairline borders
   (T tokens), Geist fonts (F2), the video accent via useAccent() — NEVER hardcode colors.
3. ALL motion frame-deterministic: useCurrentFrame + spring/interpolate. No wall-clock, no
   Math.random (use remotion's random(seed)), no external animation libs.
4. Wrap the content in <Scene bg="plain|grid|shader"> from fx.tsx (keeps clear of captions).
   Design for 1080x1920; content fits within ~950px width.
5. Do NOT touch src/auto/generated/index.ts — it is machine-generated and will pick your
   files up automatically. Do not edit any other existing file.
6. Keep it self-contained and type-safe (strict TS). No new npm dependencies.
Reply DONE when finished.`;

  try {
    await claude(prompt, { model: "opus", tools: AGENT_TOOLS, cwd: studio, timeoutMs: 12 * 60_000 });
    await writeRegistry(dir);
    let check = await tsc(studio);
    if (!check.ok) {
      // one repair attempt with the actual compiler output
      await claude(
        `Your generated scene components in src/auto/generated/ fail typecheck. Fix them (do not touch index.ts or other files):\n${check.errors}\nReply DONE when fixed.`,
        { model: "opus", tools: AGENT_TOOLS, cwd: studio, timeoutMs: 8 * 60_000 },
      );
      await writeRegistry(dir); // in case the fix renamed/added files
      check = await tsc(studio);
      if (!check.ok) throw new Error(`custom scenes failed typecheck: ${check.errors.slice(0, 300)}`);
    }

    // the visual gate: typecheck can't see overflowing text or invisible content.
    // Render a still of each component and let Opus judge it (and fix the file if needed).
    let touched = false;
    for (const c of customs) {
      const still = await renderStill(studio, videoId, c);
      if (!still) continue; // still failed but tsc passed — let it through rather than kill the reel
      const file = `src/auto/generated/${videoId}-${c.name}.tsx`;
      const verdict = await claude(
        `You built the bespoke Remotion component "${c.name}" (file: ${file}) for this spec:
${c.spec}
Props it renders with: ${JSON.stringify(c.props ?? {})}

A still from mid-scene was rendered to ${still} (1080x1920 at 0.5 scale). Read that image and
judge it like an art director: does it show what the spec asks? Is everything readable, inside
the frame (nothing clipped/overflowing/invisible), dark glassy panels with the accent color?
- If it looks right: reply exactly OK.
- If not: fix ${file} (ONLY that file), keep it type-safe, then reply FIXED.`,
        { model: "opus", tools: AGENT_TOOLS, cwd: studio, timeoutMs: 8 * 60_000 },
      );
      if (!/^\s*OK\b/i.test(verdict.trim())) touched = true;
    }
    if (touched) {
      await writeRegistry(dir);
      const again = await tsc(studio);
      if (!again.ok) throw new Error(`custom scenes broke typecheck during visual fixes: ${again.errors.slice(0, 300)}`);
    }

    // success: rewrite custom scene names to their namespaced registry keys
    return scenes.map((s) => (s.kind === "custom" && s.name ? { ...s, name: `${videoId}/${s.name}` } : s));
  } catch (e) {
    console.error("custom scene build failed — dropping customs:", (e as Error).message);
    // revert: delete everything this build created, rebuild the registry from what's left
    for (const c of await listGenerated(dir)) {
      if (!before.has(c.file)) await unlink(resolve(dir, c.file)).catch(() => {});
    }
    await writeRegistry(dir).catch(() => {});
    return scenes.filter((s) => s.kind !== "custom");
  }
}
