import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { spawn } from "node:child_process";
import { claude } from "./claude.js";
import { config } from "../config.js";

// Builds the director's bespoke "custom" scenes at render time: an agentic Opus session
// writes the component into studio/src/auto/generated/; we then typecheck, render a still
// of each component and have Opus LOOK at it (the CLAUDE.md "verify visually" rule, applied
// to the robot). Any failure deletes this build's files and rebuilds the registry — a render
// can never break, and the studio project can't be left dirty.
//
// The registry (generated/index.ts) is MACHINE-GENERATED here — agents never touch it.
// Keys are "<videoId>/<Name>" so two videos' components can't collide.

function run(cmd: string, args: string[], cwd: string, timeoutMs = 240_000): Promise<{ ok: boolean; out: string }> {
  return new Promise((res) => {
    const p = spawn(cmd, args, { cwd, shell: process.platform === "win32" });
    let out = "";
    const timer = setTimeout(() => {
      p.kill("SIGKILL");
      res({ ok: false, out: `${cmd} timed out after ${Math.round(timeoutMs / 1000)}s` });
    }, timeoutMs);
    p.stdout.on("data", (d) => (out += d));
    p.stderr.on("data", (d) => (out += d));
    p.on("error", () => { clearTimeout(timer); res({ ok: false, out: `${cmd} failed to run` }); });
    p.on("close", (code) => { clearTimeout(timer); res({ ok: code === 0, out }); });
  });
}

async function tsc(studio: string): Promise<{ ok: boolean; errors: string }> {
  const r = await run("npx", ["tsc", "--noEmit"], studio);
  return { ok: r.ok, errors: r.out.slice(0, 2000) };
}

type Gen = { file: string; videoId: string; ts: number; name: string };

async function listGenerated(dir: string): Promise<Gen[]> {
  const files = (await readdir(dir).catch(() => [] as string[])).filter((f) => /^reel-\d+-[A-Za-z0-9]+\.tsx$/.test(f));
  return files.map((f) => {
    const m = f.match(/^(reel-(\d+))-([A-Za-z0-9]+)\.tsx$/)!;
    return { file: f, videoId: m[1], ts: Number(m[2]), name: m[3] };
  });
}

async function writeRegistry(dir: string): Promise<void> {
  const comps = await listGenerated(dir);
  const src = [
    'import type * as React from "react";',
    "",
    "// MACHINE-GENERATED by bot/src/lib/studio.ts — do not edit by hand.",
    "// AutoReel resolves {\"kind\":\"custom\",\"name\":\"<videoId>/<Name>\"} via GENERATED[name].",
    ...comps.map((c, i) => `import C${i} from "./${c.file.replace(/\.tsx$/, "")}";`),
    "",
    "export const GENERATED: Record<string, React.FC<any>> = {",
    ...comps.map((c, i) => `  "${c.videoId}/${c.name}": C${i},`),
    "};",
    "",
  ].join("\n");
  await writeFile(resolve(dir, "index.ts"), src);
}

// keep only the newest KEEP videos' components — one stale component breaking (Remotion
// upgrade, API drift) would otherwise block every future custom build via project-wide tsc
async function pruneGenerated(dir: string, keep = 5): Promise<void> {
  const comps = await listGenerated(dir);
  const ids = [...new Set(comps.map((c) => c.ts))].sort((a, b) => b - a);
  const dead = new Set(ids.slice(keep));
  for (const c of comps) if (dead.has(c.ts)) await unlink(resolve(dir, c.file)).catch(() => {});
}

// Render stills of the custom scene for the visual gate — in the renderer the video will
// actually use, at arrival (springs settled) and deep into a long hold (is it still alive, or a
// frozen card?). World-style scenes now hold up to ~10s, so the late frame matters.
async function renderStills(studio: string, videoId: string, c: any, composition: string): Promise<string[]> {
  const propsPath = resolve(studio, "out", `verify-${videoId}-${c.name}.props.json`);
  await mkdir(resolve(studio, "out"), { recursive: true });
  await writeFile(
    propsPath,
    JSON.stringify({
      videoSrc: "",
      captions: [],
      scenes: [{ ...c, name: `${videoId}/${c.name}`, startMs: 0, endMs: 9000 }],
      accent: "cyan",
    }),
  );
  const out: string[] = [];
  for (const frame of [60, 240]) {
    const rel = `out/verify-${videoId}-${c.name}-${frame}.png`;
    const r = await run("npx", ["remotion", "still", composition, rel, `--props=${propsPath}`, `--frame=${frame}`, "--scale=0.5"], studio);
    if (r.ok) out.push(rel);
    else console.error(`verify still ${frame} failed for ${c.name}:`, r.out.slice(-300));
  }
  return out;
}

const AGENT_TOOLS = ["Read", "Write", "Edit", "Glob", "Grep"];

export async function buildCustomScenes(scenes: any[], videoId: string, composition = "WorldReel"): Promise<any[]> {
  const customs = scenes.filter((s) => s.kind === "custom" && s.name && s.spec);
  if (!customs.length) return scenes.filter((s) => s.kind !== "custom");

  const studio = config.studioDir;
  const dir = resolve(studio, "src/auto/generated");
  await pruneGenerated(dir);
  await writeRegistry(dir); // registry reflects the pruned set before we build on top of it
  const before = new Set((await listGenerated(dir)).map((c) => c.file));

  const brief = customs
    .map((c) => `- name: ${c.name}\n  spec: ${c.spec}\n  props it will receive: ${JSON.stringify(c.props ?? {})}`)
    .join("\n");

  const prompt = `You are building bespoke Remotion scene components for ONE video (id ${videoId})
inside this studio project (cwd = studio root). Build these:
${brief}

HOW IT WILL BE SEEN: the reel is a talking head. Each scene is an OBJECT that floats over the
creator in the upper-middle of the 1080x1920 frame while his face stays visible around it; a
camera glides from object to object. A scene can hold for up to ~10 seconds while he talks about
it. Bar: a professional Instagram reel (think Nick Saraev) — fluid, choreographed, product-grade.

REQUIREMENTS (all mandatory):
1. Read src/auto/kit.tsx and the "## kit" section of COMPONENTS.md FIRST, then src/auto/theme.ts
   and src/auto/fx.tsx. Build from the kit's primitives (surfaces, entrances, typing, counters,
   connectors, cursor, highlight, logo chips) rather than from scratch — they already carry the
   house finish. Look at one or two existing components in src/auto/v3-*.tsx or v2-*.tsx for the
   quality bar.
2. For each component: create src/auto/generated/${videoId}-<Name>.tsx with a DEFAULT export
   React.FC that takes the props above. Visual language: dark glassy panels, hairline borders
   (T tokens), Geist fonts (F2), the video accent via useAccent() — NEVER hardcode colors.
3. ALL motion frame-deterministic: useCurrentFrame + spring/interpolate. No wall-clock, no
   Math.random (use remotion's random(seed)), no external animation libs, no CSS animation.
4. Wrap the content in <Scene> from fx.tsx. Content fits a box about 1000px wide by 900px tall —
   no full-screen backgrounds (the object sits over his video).
5. CHOREOGRAPH IT: a clear entrance (~0.5-1s), the main action that shows what the spec is about,
   then SECONDARY MOTION for the rest of the hold (data flowing, a counter ticking, a cursor
   moving, a subtle pulse on the key element) so it is never a frozen card at second 8.
6. Real content only — every number, name and label comes from the props or the spec.
7. Do NOT touch src/auto/generated/index.ts — it is machine-generated and will pick your
   files up automatically. Do not edit any other existing file.
8. Keep it self-contained and type-safe (strict TS). No new npm dependencies.
Reply DONE when finished.`;

  try {
    await claude(prompt, { tools: AGENT_TOOLS, cwd: studio, timeoutMs: 12 * 60_000 });
    await writeRegistry(dir);
    let check = await tsc(studio);
    if (!check.ok) {
      // one repair attempt with the actual compiler output
      await claude(
        `Your generated scene components in src/auto/generated/ fail typecheck. Fix them (do not touch index.ts or other files):\n${check.errors}\nReply DONE when fixed.`,
        { tools: AGENT_TOOLS, cwd: studio, timeoutMs: 8 * 60_000 },
      );
      await writeRegistry(dir); // in case the fix renamed/added files
      check = await tsc(studio);
      if (!check.ok) throw new Error(`custom scenes failed typecheck: ${check.errors.slice(0, 300)}`);
    }

    // the visual gate: typecheck can't see overflowing text or invisible content.
    // Render a still of each component and let Opus judge it (and fix the file if needed).
    let touched = false;
    for (const c of customs) {
      const stills = await renderStills(studio, videoId, c, composition);
      if (!stills.length) continue; // stills failed but tsc passed — let it through rather than kill the reel
      const file = `src/auto/generated/${videoId}-${c.name}.tsx`;
      const verdict = await claude(
        `You built the bespoke Remotion component "${c.name}" (file: ${file}) for this spec:
${c.spec}
Props it renders with: ${JSON.stringify(c.props ?? {})}

Stills were rendered (1080x1920 at 0.5 scale): ${stills.join(" (at ~2s, just after arriving), ")}${stills.length > 1 ? " (at 8s, deep into a long hold)" : ""}.
Read them and judge like an art director for a professional Instagram reel: does it show what the
spec asks? Is everything readable at phone size, inside its box (nothing clipped, overflowing or
invisible), dark glassy panels with the accent colour? At 8s is it still visibly alive and
complete — not blank, not stuck mid-entrance, not a frozen empty card?
- If it looks right: reply exactly OK.
- If not: fix ${file} (ONLY that file), keep it type-safe, then reply FIXED.`,
        { tools: AGENT_TOOLS, cwd: studio, timeoutMs: 8 * 60_000 },
      );
      if (!/^\s*OK\b/i.test(verdict.trim())) touched = true;
    }
    if (touched) {
      await writeRegistry(dir);
      const again = await tsc(studio);
      if (!again.ok) throw new Error(`custom scenes broke typecheck during visual fixes: ${again.errors.slice(0, 300)}`);
    }

    // success: rewrite custom scene names to their namespaced registry keys
    return scenes.map((s) => (s.kind === "custom" && s.name ? { ...s, name: `${videoId}/${s.name}` } : s));
  } catch (e) {
    console.error("custom scene build failed — dropping customs:", (e as Error).message);
    // revert: delete everything this build created, rebuild the registry from what's left
    for (const c of await listGenerated(dir)) {
      if (!before.has(c.file)) await unlink(resolve(dir, c.file)).catch(() => {});
    }
    await writeRegistry(dir).catch(() => {});
    return scenes.filter((s) => s.kind !== "custom");
  }
}
